# Week 2



loss function computes error for a single example and cost function is averafe cist if the functions across all examples

$loss\ function: \ \mathcal{L}(\hat{y},y) = \frac{1}{2}(\hat{y}-y)^2 $

$log \ loss\ function: \ \mathcal{L}(\hat{y},y) = -ylog(\hat{y}) + (1-y)log(1-\hat{y})$

$cost\ function: \ \mathcal{J}(w,b) = \frac{1}{m} \sum^m_{i=1}L(\hat{y}^(i),y^{(i)})$

If convex cost function (i.e bowl), use gradient descent with ease 

$\mathcal{w}:=\mathcal{w}-\alpha \frac{\mathcal{dJ(w)}}{dw}=w-\alpha dw$ where $\alpha \ and\ \mathcal{dw}=\frac{\mathcal{dJ(w)}}{\mathcal{dw}}$ is the learning rate


In [19]:
import numpy as np 

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
import time 

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic = time.time()
c=np.dot(a,b)
toc=time.time()

print("Vectorised version takes "+str(1000*(toc-tic))+" ms")

tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()

print("Nonvectorised version takes "+str(1000*(toc-tic))+" ms")


Vectorised version takes 71.70391082763672 ms
Nonvectorised version takes 603.6019325256348 ms


In [5]:
A=np.array([[1,2,3],[3,4,5]])
A=A+100 #broadcasting
print("A is {} ".format(A)) # addingg in values to string
cal=A.sum(axis=0)
print("   ")

print("aggregated  is",cal)

A is [[101 102 103]
 [103 104 105]] 
   
aggregated  is [204 206 208]


In [6]:
percentage=A*100/cal.reshape(1,3)
print(percentage)
#error is max likelyhood estimation of -L(y1,y2), same as minimising L(y1,y2)

[[ 49.50980392  49.51456311  49.51923077]
 [ 50.49019608  50.48543689  50.48076923]]


In [7]:

a = np.ones((4,3)) # a.shape = (4, 3)
# b = np.random.randn(4, 1) # b.shape = (3, 2)
b = np.asarray([[1],[2],[3],[4]])
c = a*b #* and + are always element wise, use np.dot for dot


# Week 3


Components of a neural net
 
- Input 
- Hidden layer 
- Output Layer 

Equations Within Net


$\underline{a}^{[0]}=\underline{X}$ - This is the first layer of activation function - x gets passed to hiddden layer

$\underline{a}^{[1]}=\underline{X}$ - This is the first hidden layer units after one application of activation function

$z=W^{T}x+b$

$a=\sigma (z)$

never use sigmoid activation function, use tanh apart from last layer where we may need num between 0 and 1 then use sig

look into leaky relu activation function

derivative of tanhx = 1-tanhx^2

derivative (ReLU) of max(0,z)=0 if z < 0 and 1 if z > 0

derivative (Leaky ReLU) of max(0.01z,z)=0.01 if z < 0 and 1 if z > 0


#look into doing a GAN project with Sebastien 

when initialise weights use np.rand((2,2))*0.01

In [14]:
np.sum(np.array([[1,2,3],[1,2,3]]),axis=1,keepdims=True).shape #keepdims=true keeps end as (2,1) and not (2,) 

(2, 1)

# Results 

ReLU - much quikcer but less powerfull than tanh